# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14szeqO5FzYibR5axj-x4aqq-PVn1bi1J
"""

import os

print("="*42)
print(" OpenTrack — Open Source Project")
print(" Project Lead : Ozod")
print("="*42)

project = ("OpenTrack", "1.0", 2024, "Python", "Ozod")

print("Name :", project[0], "| Version :", project[1], "| Started :", project[2])
print("First 3 fields :", project[:3])
print("Language count :", project.count("Python"), "Language index :", project.index("Python"))

contributors = []

for i in range(4):
    name = input("name: ")
    role = input("role: ")
    lang = input("language: ")
    commits = input("commits: ")
    country = input("country: ")
    contributors.append({"name": name, "role": role, "language": lang, "commits": commits, "country": country})

names = [c["name"] for c in contributors]
names.sort()
print("Sorted names :", names)
print("Last name :", names[-1], "First two :", names[:2])

for c in contributors:
    c.update({"status": "Active"})

print("Contributor 1 status :", contributors[0].get("status"))

backup = contributors[0].copy()
print("Backup :", backup)

issues = []

for i in range(5):
    idd = input("id: ")
    title = input("title: ")
    typ = input("type: ")
    priority = input("priority: ")
    reporter = input("reporter: ")
    status = input("status: ")
    issues.append({"id": idd, "title": title, "type": typ, "priority": priority, "reporter": reporter, "status": status})

open_count = 0
for i in issues:
    if i["status"] == "Open":
        open_count += 1

print("Open issues :", open_count)

issues[0]["priority"] = "Critical"
print("First issue → priority updated to Critical.")

print("Last two issues :", issues[-2:])

reporters = set()
for i in issues:
    reporters.add(i["reporter"])

tech_stack = set()
for c in contributors:
    tech_stack.add(c["language"])

tech_stack.add("Go")
tech_stack.discard("C++")

print("reporters :", reporters)
print("tech_stack :", tech_stack)
print("union :", reporters.union(tech_stack))
print("intersection :", reporters.intersection(tech_stack))
print("difference :", reporters.difference(tech_stack))

all_priorities = set()
for i in issues:
    all_priorities.add(i["priority"])

if "Critical" in all_priorities:
    print("Critical present : YES — flag for immediate review.")
else:
    print("Critical present : NO")

priority_count = {}
for i in issues:
    p = i["priority"]
    if p in priority_count:
        priority_count[p] += 1
    else:
        priority_count[p] = 1

print("priority keys :", priority_count.keys())
print("priority values :", priority_count.values())

status_groups = {}
for i in issues:
    s = i["status"]
    if s not in status_groups:
        status_groups[s] = []
    status_groups[s].append(i["title"])

for k, v in status_groups.items():
    print(k, ":", v)

report_count = {}
for i in issues:
    r = i["reporter"]
    if r in report_count:
        report_count[r] += 1
    else:
        report_count[r] = 1

top_name = ""
top_val = 0
for k, v in report_count.items():
    if v > top_val:
        top_val = v
        top_name = k

print("Top reporter :", top_name, "(", top_val, "issues)")

removed = issues[0].pop("type")
print("After pop('type') :", issues[0])

folder = project[0].lower().replace(" ", "_")

if not os.path.exists(folder):
    os.mkdir(folder)
    print("Folder created :", folder)
else:
    print("Folder already exists :", folder)

print("Folder content :", os.listdir("."))

report_path = os.path.join(folder, "project_report.txt")
csv_path = os.path.join(folder, "issues.csv")

try:
    f = open(report_path, "w")
    f.write("="*42 + "\n")
    f.write(project[0] + " — PROJECT REPORT\n")
    f.write("="*42 + "\n")
    f.write(str(project) + "\n")
    f.write(str(contributors) + "\n")
    f.write(str(issues) + "\n")
    f.write("Top reporter: " + top_name + "\n")
    f.close()

    f = open(csv_path, "w")
    f.write("id,title,priority,reporter,status\n")
    for i in issues:
        f.write(f"{i['id']},{i['title']},{i['priority']},{i['reporter']},{i['status']}\n")
    f.close()

except IOError:
    print("Write error")

try:
    f = open(report_path, "r")
    print("--- read() ---")
    print(f.read())
    f.close()

    f = open(report_path, "r")
    print("--- readline() ---")
    print("Line 1 :", f.readline().strip())
    print("Line 2 :", f.readline().strip())
    f.close()

    f = open(report_path, "r")
    lines = f.readlines()
    count = 0
    for l in lines:
        if "Critical" in l or "High" in l:
            count += 1
    print("--- readlines() ---")
    print("Total lines :", len(lines), "Critical/High lines :", count)
    f.close()

except FileNotFoundError:
    print("Read error")

print("="*42)
print(f" {project[0]} — FINAL SUMMARY")
print("="*42)
print(f"Project : {project[0]} Version : {project[1]} Lead : {project[4]}")
print(f"Contributors : {len(contributors)} Names : {names}")
print(f"Tech Stack : {tech_stack}")
print(f"Issues : {len(issues)} Open : {open_count} Reporters : {len(reporters)}")
print(f"Top Reporter : {top_name} ({top_val} issues)")
for k, v in priority_count.items():
    print(f"{k}:{v}", end=" ")
print()
print(f"Report : {report_path}")
print(f"CSV : {csv_path}")
print("="*42)

urgent = [i["title"] for i in issues if i["priority"] == "Critical" or i["priority"] == "High"]
print("Urgent :", urgent, "Count :", len(urgent))

f = open(report_path, "a")
f.write("\nURGENT ISSUES\n")
for u in urgent:
    f.write(u + "\n")
f.close()

f = open(report_path, "r")
lines = f.readlines()
print("Last 6 lines:")
for l in lines[-6:]:
    print(l.strip())
f.close()